version: '3.4'

services:
  new-api:
    image: new-api-local
    container_name: new-api-local
    restart: always
    command: --log-dir /app/logs
    ports:
      - "52100:3000"
    volumes:
      - ./data-local:/data
      - ./logs-local:/app/logs
    env_file:
      - .env.local
    environment:
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true
      - DINGTALK_OAUTH_ENABLED=true
      - SERVER_ADDRESS=http://tw.ihainan.me:52100

